# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/robolab/software/Linux_Unreal_Engine_5.6.1

TARGETS = \
	VRTeleoperation-Android-DebugGame  \
	VRTeleoperation-Android-Development  \
	VRTeleoperation-Android-Shipping  \
	VRTeleoperation-Linux-DebugGame  \
	VRTeleoperation-Linux-Development  \
	VRTeleoperation-Linux-Shipping  \
	VRTeleoperation-LinuxArm64-DebugGame  \
	VRTeleoperation-LinuxArm64-Development  \
	VRTeleoperation-LinuxArm64-Shipping  \
	VRTeleoperation \
	VRTeleoperationEditor-Linux-DebugGame  \
	VRTeleoperationEditor-Linux-Development  \
	VRTeleoperationEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend VRTeleoperationEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug VRTeleoperationEditor-Linux-Debug


VRTeleoperation-Android-DebugGame:
	 $(BUILD) VRTeleoperation Android DebugGame  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-Android-Development:
	 $(BUILD) VRTeleoperation Android Development  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-Android-Shipping:
	 $(BUILD) VRTeleoperation Android Shipping  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-Linux-DebugGame:
	 $(BUILD) VRTeleoperation Linux DebugGame  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-Linux-Development:
	 $(BUILD) VRTeleoperation Linux Development  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-Linux-Shipping:
	 $(BUILD) VRTeleoperation Linux Shipping  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-LinuxArm64-DebugGame:
	 $(BUILD) VRTeleoperation LinuxArm64 DebugGame  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-LinuxArm64-Development:
	 $(BUILD) VRTeleoperation LinuxArm64 Development  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation-LinuxArm64-Shipping:
	 $(BUILD) VRTeleoperation LinuxArm64 Shipping  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperation: VRTeleoperation-Linux-Development

VRTeleoperationEditor-Linux-DebugGame:
	 $(BUILD) VRTeleoperationEditor Linux DebugGame  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperationEditor-Linux-Development:
	 $(BUILD) VRTeleoperationEditor Linux Development  -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" $(ARGS)

VRTeleoperationEditor: VRTeleoperationEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/robolab/Documents/Unreal Projects/VRTeleoperation/VRTeleoperation.uproject" -Game 

.PHONY: $(TARGETS)
