//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: KinovaArmPub.ice
//  Source: KinovaArmPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPKINOVAARMPUB_ICE
#define ROBOCOMPKINOVAARMPUB_ICE
#include <KinovaArm.ice>
module RoboCompKinovaArmPub
{
	interface KinovaArmPub
	{
		void newArmState (RoboCompKinovaArm::TPose armState);
		void sendJointsWithAngle (RoboCompKinovaArm::TJointAngles angles);
	};
};

#endif
