//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Navigator.ice
//  Source: Navigator.idsl
//
//******************************************************************
#ifndef ROBOCOMPNAVIGATOR_ICE
#define ROBOCOMPNAVIGATOR_ICE
module RoboCompNavigator
{
	struct TPoint
	{
		float x;
		float y;
	};
	sequence <TPoint> TPath;
	struct Result
	{
		TPath path;
		long timestamp;
		string errorMsg;
		bool valid;
	};
	sequence <float> TCov;
	struct Pose
	{
		float x;
		float y;
		float theta;
		TCov cov;
	};
	enum NavigationState { 
	        IDLE,           // No target set, robot stopped
	        NAVIGATING,     // Moving towards target
	        PAUSED,         // Stopped but target still active (can resume)
	        REACHED,        // Target reached, robot stopped
	        BLOCKED,        // Path blocked, attempting to replan
	        ERROR           // Critical error (localization lost, etc.)
	     };
	struct NavigationStatus
	{
		NavigationState state;
		TPoint currentTarget;
		TPoint currentPosition;
		float currentOrientation;
		float distanceToTarget;
		float estimatedTime;
		float currentSpeed;
		int pathWaypointsRemaining;
		string statusMessage;
	};
	sequence <TPoint> TLayout;
	struct TObject
	{
		string name;
		TLayout layout;
	};
	sequence <TObject> TObjects;
	struct LayoutData
	{
		TLayout layout;
		TObjects objects;
	};
	struct TPose
	{
		float x;
		float y;
		float r;
	};
	interface Navigator
	{
		LayoutData getLayout ();
		Result getPath (TPoint source, TPoint target, float safety);
		TPose getRobotPose ();
		NavigationStatus getStatus ();
		TPoint gotoObject (string object);
		TPoint gotoPoint (TPoint target);
		TPose gotoPose (TPose pose);
		void resume ();
		void stop ();
	};
};

#endif
