//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: VRControllerPub.ice
//  Source: VRControllerPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPVRCONTROLLERPUB_ICE
#define ROBOCOMPVRCONTROLLERPUB_ICE
module RoboCompVRControllerPub
{
	struct Pose
	{
		float x;
		float y;
		float z;
		float rx;
		float ry;
		float rz;
		float qrx;
		float qry;
		float qrz;
		float qrw;
	};
	struct Controller
	{
		float trigger;
		float grab;
		float x;
		float y;
		float thumbstickCapTouch;
		bool aButton;
		float aButtonCapTouch;
		bool bButton;
		float bButtonCapTouch;
	};
	struct Haptic
	{
		float intensity;
		float frequency;
	};
	interface VRControllerPub
	{
		void sendControllers (Controller left, Controller right);
		void sendHaptics (Haptic left, Haptic right);
		void sendPoses (Pose head, Pose left, Pose right);
	};
};

#endif
