//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VRController.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <VRController.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompVRController_VRController_ids[2] =
{
    "::Ice::Object",
    "::RoboCompVRController::VRController"
};
const ::std::string iceC_RoboCompVRController_VRController_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendControllers",
    "sendPose"
};
const ::std::string iceC_RoboCompVRController_VRController_sendControllers_name = "sendControllers";
const ::std::string iceC_RoboCompVRController_VRController_sendPose_name = "sendPose";

}

bool
RoboCompVRController::VRController::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompVRController_VRController_ids, iceC_RoboCompVRController_VRController_ids + 2, s);
}

::std::vector<::std::string>
RoboCompVRController::VRController::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompVRController_VRController_ids[0], &iceC_RoboCompVRController_VRController_ids[2]);
}

::std::string
RoboCompVRController::VRController::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompVRController::VRController::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompVRController::VRController";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompVRController::VRController::_iceD_sendControllers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    Controller iceP_left;
    Controller iceP_right;
    istr->readAll(iceP_left, iceP_right);
    inS.endReadParams();
    this->sendControllers(::std::move(iceP_left), ::std::move(iceP_right), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRController::VRController::_iceD_sendPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    Pose iceP_head;
    Pose iceP_left;
    Pose iceP_right;
    istr->readAll(iceP_head, iceP_left, iceP_right);
    inS.endReadParams();
    this->sendPose(::std::move(iceP_head), ::std::move(iceP_left), ::std::move(iceP_right), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRController::VRController::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompVRController_VRController_ops, iceC_RoboCompVRController_VRController_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompVRController_VRController_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendControllers(in, current);
        }
        case 5:
        {
            return _iceD_sendPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRController::VRControllerPrx::_iceI_sendControllers(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const Controller& iceP_left, const Controller& iceP_right, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompVRController_VRController_sendControllers_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_left, iceP_right);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRController::VRControllerPrx::_iceI_sendPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const Pose& iceP_head, const Pose& iceP_left, const Pose& iceP_right, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompVRController_VRController_sendPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_head, iceP_left, iceP_right);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompVRController::VRControllerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<VRControllerPrx>();
}
/// \endcond

const ::std::string&
RoboCompVRController::VRControllerPrx::ice_staticId()
{
    return VRController::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompVRController_VRController_sendControllers_name = "sendControllers";

const ::std::string iceC_RoboCompVRController_VRController_sendPose_name = "sendPose";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompVRController::upCast(VRController* p) { return p; }

void
::IceProxy::RoboCompVRController::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< VRController>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new VRController;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompVRController::VRController::_iceI_begin_sendControllers(const ::RoboCompVRController::Controller& iceP_left, const ::RoboCompVRController::Controller& iceP_right, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompVRController_VRController_sendControllers_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompVRController_VRController_sendControllers_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_left);
        ostr->write(iceP_right);
        result->endWriteParams();
        result->invoke(iceC_RoboCompVRController_VRController_sendControllers_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompVRController::VRController::end_sendControllers(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompVRController_VRController_sendControllers_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompVRController::VRController::_iceI_begin_sendPose(const ::RoboCompVRController::Pose& iceP_head, const ::RoboCompVRController::Pose& iceP_left, const ::RoboCompVRController::Pose& iceP_right, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompVRController_VRController_sendPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompVRController_VRController_sendPose_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_head);
        ostr->write(iceP_left);
        ostr->write(iceP_right);
        result->endWriteParams();
        result->invoke(iceC_RoboCompVRController_VRController_sendPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompVRController::VRController::end_sendPose(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompVRController_VRController_sendPose_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompVRController::VRController::_newInstance() const
{
    return new VRController;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompVRController::VRController::ice_staticId()
{
    return ::RoboCompVRController::VRController::ice_staticId();
}

RoboCompVRController::VRController::~VRController()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompVRController::upCast(VRController* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompVRController_VRController_ids[2] =
{
    "::Ice::Object",
    "::RoboCompVRController::VRController"
};

}

bool
RoboCompVRController::VRController::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompVRController_VRController_ids, iceC_RoboCompVRController_VRController_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompVRController::VRController::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompVRController_VRController_ids[0], &iceC_RoboCompVRController_VRController_ids[2]);
}

const ::std::string&
RoboCompVRController::VRController::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompVRController::VRController::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompVRController::VRController";
    return typeId;
#else
    return iceC_RoboCompVRController_VRController_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompVRController::VRController::_iceD_sendControllers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    Controller iceP_left;
    Controller iceP_right;
    istr->read(iceP_left);
    istr->read(iceP_right);
    inS.endReadParams();
    this->sendControllers(iceP_left, iceP_right, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRController::VRController::_iceD_sendPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    Pose iceP_head;
    Pose iceP_left;
    Pose iceP_right;
    istr->read(iceP_head);
    istr->read(iceP_left);
    istr->read(iceP_right);
    inS.endReadParams();
    this->sendPose(iceP_head, iceP_left, iceP_right, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompVRController_VRController_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendControllers",
    "sendPose"
};

}

/// \cond INTERNAL
bool
RoboCompVRController::VRController::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompVRController_VRController_all, iceC_RoboCompVRController_VRController_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompVRController_VRController_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendControllers(in, current);
        }
        case 5:
        {
            return _iceD_sendPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompVRController::VRController::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< VRController, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompVRController::VRController::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< VRController, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRController::_icePatchObjectPtr(VRControllerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = VRControllerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(VRController::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
