//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VRControllerPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __VRControllerPub_h__
#define __VRControllerPub_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompVRControllerPub
{

class VRControllerPub;
class VRControllerPubPrx;

}

namespace RoboCompVRControllerPub
{

struct Pose
{
    float x;
    float y;
    float z;
    float rx;
    float ry;
    float rz;
    float qrx;
    float qry;
    float qrz;
    float qrw;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&, const float&, const float&, const float&, const float&, const float&, const float&, const float&, const float&, const float&> ice_tuple() const
    {
        return std::tie(x, y, z, rx, ry, rz, qrx, qry, qrz, qrw);
    }
};

struct Controller
{
    float trigger;
    float grab;
    float x;
    float y;
    float thumbstickCapTouch;
    bool aButton;
    float aButtonCapTouch;
    bool bButton;
    float bButtonCapTouch;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&, const float&, const float&, const float&, const float&, const bool&, const float&, const bool&, const float&> ice_tuple() const
    {
        return std::tie(trigger, grab, x, y, thumbstickCapTouch, aButton, aButtonCapTouch, bButton, bButtonCapTouch);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompVRControllerPub
{

class VRControllerPub : public virtual ::Ice::Object
{
public:

    using ProxyType = VRControllerPubPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void sendControllers(Controller left, Controller right, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_sendControllers(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void sendPoses(Pose head, Pose left, Pose right, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_sendPoses(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompVRControllerPub
{

class VRControllerPubPrx : public virtual ::Ice::Proxy<VRControllerPubPrx, ::Ice::ObjectPrx>
{
public:

    void sendControllers(const Controller& left, const Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &VRControllerPubPrx::_iceI_sendControllers, left, right, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto sendControllersAsync(const Controller& left, const Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &VRControllerPubPrx::_iceI_sendControllers, left, right, context);
    }

    ::std::function<void()>
    sendControllersAsync(const Controller& left, const Controller& right,
                         ::std::function<void()> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(std::move(response), std::move(ex), std::move(sent), this, &RoboCompVRControllerPub::VRControllerPubPrx::_iceI_sendControllers, left, right, context);
    }

    /// \cond INTERNAL
    void _iceI_sendControllers(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const Controller&, const Controller&, const ::Ice::Context&);
    /// \endcond

    void sendPoses(const Pose& head, const Pose& left, const Pose& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &VRControllerPubPrx::_iceI_sendPoses, head, left, right, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto sendPosesAsync(const Pose& head, const Pose& left, const Pose& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &VRControllerPubPrx::_iceI_sendPoses, head, left, right, context);
    }

    ::std::function<void()>
    sendPosesAsync(const Pose& head, const Pose& left, const Pose& right,
                   ::std::function<void()> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(std::move(response), std::move(ex), std::move(sent), this, &RoboCompVRControllerPub::VRControllerPubPrx::_iceI_sendPoses, head, left, right, context);
    }

    /// \cond INTERNAL
    void _iceI_sendPoses(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const Pose&, const Pose&, const Pose&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    VRControllerPubPrx() = default;
    friend ::std::shared_ptr<VRControllerPubPrx> IceInternal::createProxy<VRControllerPubPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::RoboCompVRControllerPub::Pose>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 40;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompVRControllerPub::Pose, S>
{
    static void read(S* istr, ::RoboCompVRControllerPub::Pose& v)
    {
        istr->readAll(v.x, v.y, v.z, v.rx, v.ry, v.rz, v.qrx, v.qry, v.qrz, v.qrw);
    }
};

template<>
struct StreamableTraits<::RoboCompVRControllerPub::Controller>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 30;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompVRControllerPub::Controller, S>
{
    static void read(S* istr, ::RoboCompVRControllerPub::Controller& v)
    {
        istr->readAll(v.trigger, v.grab, v.x, v.y, v.thumbstickCapTouch, v.aButton, v.aButtonCapTouch, v.bButton, v.bButtonCapTouch);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompVRControllerPub
{

using VRControllerPubPtr = ::std::shared_ptr<VRControllerPub>;
using VRControllerPubPrxPtr = ::std::shared_ptr<VRControllerPubPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompVRControllerPub
{

class VRControllerPub;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< VRControllerPub>&);
::IceProxy::Ice::Object* upCast(VRControllerPub*);
/// \endcond

}

}

namespace RoboCompVRControllerPub
{

class VRControllerPub;
/// \cond INTERNAL
::Ice::Object* upCast(VRControllerPub*);
/// \endcond
typedef ::IceInternal::Handle< VRControllerPub> VRControllerPubPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompVRControllerPub::VRControllerPub> VRControllerPubPrx;
typedef VRControllerPubPrx VRControllerPubPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(VRControllerPubPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompVRControllerPub
{

struct Pose
{
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float z;
    ::Ice::Float rx;
    ::Ice::Float ry;
    ::Ice::Float rz;
    ::Ice::Float qrx;
    ::Ice::Float qry;
    ::Ice::Float qrz;
    ::Ice::Float qrw;
};

struct Controller
{
    ::Ice::Float trigger;
    ::Ice::Float grab;
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float thumbstickCapTouch;
    bool aButton;
    ::Ice::Float aButtonCapTouch;
    bool bButton;
    ::Ice::Float bButtonCapTouch;
};

}

namespace RoboCompVRControllerPub
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 * Create a wrapper instance by calling ::RoboCompVRControllerPub::newCallback_VRControllerPub_sendControllers.
 */
class Callback_VRControllerPub_sendControllers_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_VRControllerPub_sendControllers_Base> Callback_VRControllerPub_sendControllersPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 * Create a wrapper instance by calling ::RoboCompVRControllerPub::newCallback_VRControllerPub_sendPoses.
 */
class Callback_VRControllerPub_sendPoses_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_VRControllerPub_sendPoses_Base> Callback_VRControllerPub_sendPosesPtr;

}

namespace IceProxy
{

namespace RoboCompVRControllerPub
{

class VRControllerPub : public virtual ::Ice::Proxy<VRControllerPub, ::IceProxy::Ice::Object>
{
public:

    void sendControllers(const ::RoboCompVRControllerPub::Controller& left, const ::RoboCompVRControllerPub::Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_sendControllers(_iceI_begin_sendControllers(left, right, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_sendControllers(const ::RoboCompVRControllerPub::Controller& left, const ::RoboCompVRControllerPub::Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_sendControllers(left, right, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendControllers(const ::RoboCompVRControllerPub::Controller& left, const ::RoboCompVRControllerPub::Controller& right, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendControllers(left, right, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendControllers(const ::RoboCompVRControllerPub::Controller& left, const ::RoboCompVRControllerPub::Controller& right, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendControllers(left, right, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendControllers(const ::RoboCompVRControllerPub::Controller& left, const ::RoboCompVRControllerPub::Controller& right, const ::RoboCompVRControllerPub::Callback_VRControllerPub_sendControllersPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendControllers(left, right, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendControllers(const ::RoboCompVRControllerPub::Controller& left, const ::RoboCompVRControllerPub::Controller& right, const ::Ice::Context& context, const ::RoboCompVRControllerPub::Callback_VRControllerPub_sendControllersPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendControllers(left, right, context, cb, cookie);
    }

    void end_sendControllers(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_sendControllers(const ::RoboCompVRControllerPub::Controller&, const ::RoboCompVRControllerPub::Controller&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void sendPoses(const ::RoboCompVRControllerPub::Pose& head, const ::RoboCompVRControllerPub::Pose& left, const ::RoboCompVRControllerPub::Pose& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_sendPoses(_iceI_begin_sendPoses(head, left, right, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_sendPoses(const ::RoboCompVRControllerPub::Pose& head, const ::RoboCompVRControllerPub::Pose& left, const ::RoboCompVRControllerPub::Pose& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_sendPoses(head, left, right, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendPoses(const ::RoboCompVRControllerPub::Pose& head, const ::RoboCompVRControllerPub::Pose& left, const ::RoboCompVRControllerPub::Pose& right, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendPoses(head, left, right, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendPoses(const ::RoboCompVRControllerPub::Pose& head, const ::RoboCompVRControllerPub::Pose& left, const ::RoboCompVRControllerPub::Pose& right, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendPoses(head, left, right, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendPoses(const ::RoboCompVRControllerPub::Pose& head, const ::RoboCompVRControllerPub::Pose& left, const ::RoboCompVRControllerPub::Pose& right, const ::RoboCompVRControllerPub::Callback_VRControllerPub_sendPosesPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendPoses(head, left, right, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendPoses(const ::RoboCompVRControllerPub::Pose& head, const ::RoboCompVRControllerPub::Pose& left, const ::RoboCompVRControllerPub::Pose& right, const ::Ice::Context& context, const ::RoboCompVRControllerPub::Callback_VRControllerPub_sendPosesPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendPoses(head, left, right, context, cb, cookie);
    }

    void end_sendPoses(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_sendPoses(const ::RoboCompVRControllerPub::Pose&, const ::RoboCompVRControllerPub::Pose&, const ::RoboCompVRControllerPub::Pose&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompVRControllerPub
{

class VRControllerPub : public virtual ::Ice::Object
{
public:

    typedef VRControllerPubPrx ProxyType;
    typedef VRControllerPubPtr PointerType;

    virtual ~VRControllerPub();

#ifdef ICE_CPP11_COMPILER
    VRControllerPub() = default;
    VRControllerPub(const VRControllerPub&) = default;
    VRControllerPub& operator=(const VRControllerPub&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void sendControllers(const Controller& left, const Controller& right, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_sendControllers(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void sendPoses(const Pose& head, const Pose& left, const Pose& right, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_sendPoses(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const VRControllerPub& lhs, const VRControllerPub& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const VRControllerPub& lhs, const VRControllerPub& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompVRControllerPub::Pose>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 40;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompVRControllerPub::Pose, S>
{
    static void write(S* ostr, const ::RoboCompVRControllerPub::Pose& v)
    {
        ostr->write(v.x);
        ostr->write(v.y);
        ostr->write(v.z);
        ostr->write(v.rx);
        ostr->write(v.ry);
        ostr->write(v.rz);
        ostr->write(v.qrx);
        ostr->write(v.qry);
        ostr->write(v.qrz);
        ostr->write(v.qrw);
    }
};

template<typename S>
struct StreamReader< ::RoboCompVRControllerPub::Pose, S>
{
    static void read(S* istr, ::RoboCompVRControllerPub::Pose& v)
    {
        istr->read(v.x);
        istr->read(v.y);
        istr->read(v.z);
        istr->read(v.rx);
        istr->read(v.ry);
        istr->read(v.rz);
        istr->read(v.qrx);
        istr->read(v.qry);
        istr->read(v.qrz);
        istr->read(v.qrw);
    }
};

template<>
struct StreamableTraits< ::RoboCompVRControllerPub::Controller>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 30;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompVRControllerPub::Controller, S>
{
    static void write(S* ostr, const ::RoboCompVRControllerPub::Controller& v)
    {
        ostr->write(v.trigger);
        ostr->write(v.grab);
        ostr->write(v.x);
        ostr->write(v.y);
        ostr->write(v.thumbstickCapTouch);
        ostr->write(v.aButton);
        ostr->write(v.aButtonCapTouch);
        ostr->write(v.bButton);
        ostr->write(v.bButtonCapTouch);
    }
};

template<typename S>
struct StreamReader< ::RoboCompVRControllerPub::Controller, S>
{
    static void read(S* istr, ::RoboCompVRControllerPub::Controller& v)
    {
        istr->read(v.trigger);
        istr->read(v.grab);
        istr->read(v.x);
        istr->read(v.y);
        istr->read(v.thumbstickCapTouch);
        istr->read(v.aButton);
        istr->read(v.aButtonCapTouch);
        istr->read(v.bButton);
        istr->read(v.bButtonCapTouch);
    }
};

}
/// \endcond

namespace RoboCompVRControllerPub
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 * Create a wrapper instance by calling ::RoboCompVRControllerPub::newCallback_VRControllerPub_sendControllers.
 */
template<class T>
class CallbackNC_VRControllerPub_sendControllers : public Callback_VRControllerPub_sendControllers_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_VRControllerPub_sendControllers(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendControllers<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendControllers<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendControllers<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendControllers<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 * Create a wrapper instance by calling ::RoboCompVRControllerPub::newCallback_VRControllerPub_sendControllers.
 */
template<class T, typename CT>
class Callback_VRControllerPub_sendControllers : public Callback_VRControllerPub_sendControllers_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_VRControllerPub_sendControllers(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T, typename CT> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendControllers<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T, typename CT> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendControllers<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T, typename CT> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendControllers<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendControllers.
 */
template<class T, typename CT> Callback_VRControllerPub_sendControllersPtr
newCallback_VRControllerPub_sendControllers(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendControllers<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 * Create a wrapper instance by calling ::RoboCompVRControllerPub::newCallback_VRControllerPub_sendPoses.
 */
template<class T>
class CallbackNC_VRControllerPub_sendPoses : public Callback_VRControllerPub_sendPoses_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_VRControllerPub_sendPoses(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendPoses<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendPoses<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendPoses<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRControllerPub_sendPoses<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 * Create a wrapper instance by calling ::RoboCompVRControllerPub::newCallback_VRControllerPub_sendPoses.
 */
template<class T, typename CT>
class Callback_VRControllerPub_sendPoses : public Callback_VRControllerPub_sendPoses_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_VRControllerPub_sendPoses(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T, typename CT> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendPoses<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T, typename CT> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendPoses<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T, typename CT> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendPoses<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRControllerPub::VRControllerPub::begin_sendPoses.
 */
template<class T, typename CT> Callback_VRControllerPub_sendPosesPtr
newCallback_VRControllerPub_sendPoses(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRControllerPub_sendPoses<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
