//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VRController.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __VRController_h__
#define __VRController_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompVRController
{

class VRController;
class VRControllerPrx;

}

namespace RoboCompVRController
{

struct Pose
{
    float x;
    float y;
    float z;
    float qrx;
    float qry;
    float qrz;
    float qrw;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&, const float&, const float&, const float&, const float&, const float&, const float&> ice_tuple() const
    {
        return std::tie(x, y, z, qrx, qry, qrz, qrw);
    }
};

struct Controller
{
    ::RoboCompVRController::Pose pose;
    float trigger;
    float grab;
    float x;
    float y;
    float thumbstickCapTouch;
    float aButtonCapTouch;
    float bButtonCapTouch;
    bool aButton;
    bool bButton;
    bool thumbstickButton;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::RoboCompVRController::Pose&, const float&, const float&, const float&, const float&, const float&, const float&, const float&, const bool&, const bool&, const bool&> ice_tuple() const
    {
        return std::tie(pose, trigger, grab, x, y, thumbstickCapTouch, aButtonCapTouch, bButtonCapTouch, aButton, bButton, thumbstickButton);
    }
};

struct Haptic
{
    float intensity;
    float frequency;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&, const float&> ice_tuple() const
    {
        return std::tie(intensity, frequency);
    }
};

struct Haptics
{
    ::RoboCompVRController::Haptic left;
    ::RoboCompVRController::Haptic right;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::RoboCompVRController::Haptic&, const ::RoboCompVRController::Haptic&> ice_tuple() const
    {
        return std::tie(left, right);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompVRController
{

class VRController : public virtual ::Ice::Object
{
public:

    using ProxyType = VRControllerPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual Haptics sendDataReceiveHaptics(Pose head, Controller left, Controller right, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_sendDataReceiveHaptics(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompVRController
{

class VRControllerPrx : public virtual ::Ice::Proxy<VRControllerPrx, ::Ice::ObjectPrx>
{
public:

    Haptics sendDataReceiveHaptics(const Pose& head, const Controller& left, const Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompVRController::Haptics>(true, this, &VRControllerPrx::_iceI_sendDataReceiveHaptics, head, left, right, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto sendDataReceiveHapticsAsync(const Pose& head, const Controller& left, const Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompVRController::Haptics>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompVRController::Haptics, P>(false, this, &VRControllerPrx::_iceI_sendDataReceiveHaptics, head, left, right, context);
    }

    ::std::function<void()>
    sendDataReceiveHapticsAsync(const Pose& head, const Controller& left, const Controller& right,
                                ::std::function<void(::RoboCompVRController::Haptics)> response,
                                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                                ::std::function<void(bool)> sent = nullptr,
                                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompVRController::Haptics>(std::move(response), std::move(ex), std::move(sent), this, &RoboCompVRController::VRControllerPrx::_iceI_sendDataReceiveHaptics, head, left, right, context);
    }

    /// \cond INTERNAL
    void _iceI_sendDataReceiveHaptics(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompVRController::Haptics>>&, const Pose&, const Controller&, const Controller&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    VRControllerPrx() = default;
    friend ::std::shared_ptr<VRControllerPrx> IceInternal::createProxy<VRControllerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::RoboCompVRController::Pose>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 28;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompVRController::Pose, S>
{
    static void read(S* istr, ::RoboCompVRController::Pose& v)
    {
        istr->readAll(v.x, v.y, v.z, v.qrx, v.qry, v.qrz, v.qrw);
    }
};

template<>
struct StreamableTraits<::RoboCompVRController::Controller>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 59;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompVRController::Controller, S>
{
    static void read(S* istr, ::RoboCompVRController::Controller& v)
    {
        istr->readAll(v.pose, v.trigger, v.grab, v.x, v.y, v.thumbstickCapTouch, v.aButtonCapTouch, v.bButtonCapTouch, v.aButton, v.bButton, v.thumbstickButton);
    }
};

template<>
struct StreamableTraits<::RoboCompVRController::Haptic>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 8;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompVRController::Haptic, S>
{
    static void read(S* istr, ::RoboCompVRController::Haptic& v)
    {
        istr->readAll(v.intensity, v.frequency);
    }
};

template<>
struct StreamableTraits<::RoboCompVRController::Haptics>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 16;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompVRController::Haptics, S>
{
    static void read(S* istr, ::RoboCompVRController::Haptics& v)
    {
        istr->readAll(v.left, v.right);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompVRController
{

using VRControllerPtr = ::std::shared_ptr<VRController>;
using VRControllerPrxPtr = ::std::shared_ptr<VRControllerPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompVRController
{

class VRController;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< VRController>&);
::IceProxy::Ice::Object* upCast(VRController*);
/// \endcond

}

}

namespace RoboCompVRController
{

class VRController;
/// \cond INTERNAL
::Ice::Object* upCast(VRController*);
/// \endcond
typedef ::IceInternal::Handle< VRController> VRControllerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompVRController::VRController> VRControllerPrx;
typedef VRControllerPrx VRControllerPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(VRControllerPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompVRController
{

struct Pose
{
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float z;
    ::Ice::Float qrx;
    ::Ice::Float qry;
    ::Ice::Float qrz;
    ::Ice::Float qrw;
};

struct Controller
{
    ::RoboCompVRController::Pose pose;
    ::Ice::Float trigger;
    ::Ice::Float grab;
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float thumbstickCapTouch;
    ::Ice::Float aButtonCapTouch;
    ::Ice::Float bButtonCapTouch;
    bool aButton;
    bool bButton;
    bool thumbstickButton;
};

struct Haptic
{
    ::Ice::Float intensity;
    ::Ice::Float frequency;
};

struct Haptics
{
    ::RoboCompVRController::Haptic left;
    ::RoboCompVRController::Haptic right;
};

}

namespace RoboCompVRController
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 * Create a wrapper instance by calling ::RoboCompVRController::newCallback_VRController_sendDataReceiveHaptics.
 */
class Callback_VRController_sendDataReceiveHaptics_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_VRController_sendDataReceiveHaptics_Base> Callback_VRController_sendDataReceiveHapticsPtr;

}

namespace IceProxy
{

namespace RoboCompVRController
{

class VRController : public virtual ::Ice::Proxy<VRController, ::IceProxy::Ice::Object>
{
public:

    ::RoboCompVRController::Haptics sendDataReceiveHaptics(const ::RoboCompVRController::Pose& head, const ::RoboCompVRController::Controller& left, const ::RoboCompVRController::Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_sendDataReceiveHaptics(_iceI_begin_sendDataReceiveHaptics(head, left, right, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_sendDataReceiveHaptics(const ::RoboCompVRController::Pose& head, const ::RoboCompVRController::Controller& left, const ::RoboCompVRController::Controller& right, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_sendDataReceiveHaptics(head, left, right, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendDataReceiveHaptics(const ::RoboCompVRController::Pose& head, const ::RoboCompVRController::Controller& left, const ::RoboCompVRController::Controller& right, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendDataReceiveHaptics(head, left, right, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendDataReceiveHaptics(const ::RoboCompVRController::Pose& head, const ::RoboCompVRController::Controller& left, const ::RoboCompVRController::Controller& right, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendDataReceiveHaptics(head, left, right, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendDataReceiveHaptics(const ::RoboCompVRController::Pose& head, const ::RoboCompVRController::Controller& left, const ::RoboCompVRController::Controller& right, const ::RoboCompVRController::Callback_VRController_sendDataReceiveHapticsPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendDataReceiveHaptics(head, left, right, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_sendDataReceiveHaptics(const ::RoboCompVRController::Pose& head, const ::RoboCompVRController::Controller& left, const ::RoboCompVRController::Controller& right, const ::Ice::Context& context, const ::RoboCompVRController::Callback_VRController_sendDataReceiveHapticsPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sendDataReceiveHaptics(head, left, right, context, cb, cookie);
    }

    ::RoboCompVRController::Haptics end_sendDataReceiveHaptics(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_sendDataReceiveHaptics(const ::RoboCompVRController::Pose&, const ::RoboCompVRController::Controller&, const ::RoboCompVRController::Controller&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompVRController
{

class VRController : public virtual ::Ice::Object
{
public:

    typedef VRControllerPrx ProxyType;
    typedef VRControllerPtr PointerType;

    virtual ~VRController();

#ifdef ICE_CPP11_COMPILER
    VRController() = default;
    VRController(const VRController&) = default;
    VRController& operator=(const VRController&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual Haptics sendDataReceiveHaptics(const Pose& head, const Controller& left, const Controller& right, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_sendDataReceiveHaptics(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const VRController& lhs, const VRController& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const VRController& lhs, const VRController& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompVRController::Pose>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 28;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompVRController::Pose, S>
{
    static void write(S* ostr, const ::RoboCompVRController::Pose& v)
    {
        ostr->write(v.x);
        ostr->write(v.y);
        ostr->write(v.z);
        ostr->write(v.qrx);
        ostr->write(v.qry);
        ostr->write(v.qrz);
        ostr->write(v.qrw);
    }
};

template<typename S>
struct StreamReader< ::RoboCompVRController::Pose, S>
{
    static void read(S* istr, ::RoboCompVRController::Pose& v)
    {
        istr->read(v.x);
        istr->read(v.y);
        istr->read(v.z);
        istr->read(v.qrx);
        istr->read(v.qry);
        istr->read(v.qrz);
        istr->read(v.qrw);
    }
};

template<>
struct StreamableTraits< ::RoboCompVRController::Controller>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 59;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompVRController::Controller, S>
{
    static void write(S* ostr, const ::RoboCompVRController::Controller& v)
    {
        ostr->write(v.pose);
        ostr->write(v.trigger);
        ostr->write(v.grab);
        ostr->write(v.x);
        ostr->write(v.y);
        ostr->write(v.thumbstickCapTouch);
        ostr->write(v.aButtonCapTouch);
        ostr->write(v.bButtonCapTouch);
        ostr->write(v.aButton);
        ostr->write(v.bButton);
        ostr->write(v.thumbstickButton);
    }
};

template<typename S>
struct StreamReader< ::RoboCompVRController::Controller, S>
{
    static void read(S* istr, ::RoboCompVRController::Controller& v)
    {
        istr->read(v.pose);
        istr->read(v.trigger);
        istr->read(v.grab);
        istr->read(v.x);
        istr->read(v.y);
        istr->read(v.thumbstickCapTouch);
        istr->read(v.aButtonCapTouch);
        istr->read(v.bButtonCapTouch);
        istr->read(v.aButton);
        istr->read(v.bButton);
        istr->read(v.thumbstickButton);
    }
};

template<>
struct StreamableTraits< ::RoboCompVRController::Haptic>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 8;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompVRController::Haptic, S>
{
    static void write(S* ostr, const ::RoboCompVRController::Haptic& v)
    {
        ostr->write(v.intensity);
        ostr->write(v.frequency);
    }
};

template<typename S>
struct StreamReader< ::RoboCompVRController::Haptic, S>
{
    static void read(S* istr, ::RoboCompVRController::Haptic& v)
    {
        istr->read(v.intensity);
        istr->read(v.frequency);
    }
};

template<>
struct StreamableTraits< ::RoboCompVRController::Haptics>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 16;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompVRController::Haptics, S>
{
    static void write(S* ostr, const ::RoboCompVRController::Haptics& v)
    {
        ostr->write(v.left);
        ostr->write(v.right);
    }
};

template<typename S>
struct StreamReader< ::RoboCompVRController::Haptics, S>
{
    static void read(S* istr, ::RoboCompVRController::Haptics& v)
    {
        istr->read(v.left);
        istr->read(v.right);
    }
};

}
/// \endcond

namespace RoboCompVRController
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 * Create a wrapper instance by calling ::RoboCompVRController::newCallback_VRController_sendDataReceiveHaptics.
 */
template<class T>
class CallbackNC_VRController_sendDataReceiveHaptics : public Callback_VRController_sendDataReceiveHaptics_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const Haptics&);

    CallbackNC_VRController_sendDataReceiveHaptics(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        VRControllerPrx proxy = VRControllerPrx::uncheckedCast(result->getProxy());
        Haptics ret;
        try
        {
            ret = proxy->end_sendDataReceiveHaptics(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 */
template<class T> Callback_VRController_sendDataReceiveHapticsPtr
newCallback_VRController_sendDataReceiveHaptics(const IceUtil::Handle<T>& instance, void (T::*cb)(const Haptics&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRController_sendDataReceiveHaptics<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 */
template<class T> Callback_VRController_sendDataReceiveHapticsPtr
newCallback_VRController_sendDataReceiveHaptics(T* instance, void (T::*cb)(const Haptics&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_VRController_sendDataReceiveHaptics<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 * Create a wrapper instance by calling ::RoboCompVRController::newCallback_VRController_sendDataReceiveHaptics.
 */
template<class T, typename CT>
class Callback_VRController_sendDataReceiveHaptics : public Callback_VRController_sendDataReceiveHaptics_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const Haptics&, const CT&);

    Callback_VRController_sendDataReceiveHaptics(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        VRControllerPrx proxy = VRControllerPrx::uncheckedCast(result->getProxy());
        Haptics ret;
        try
        {
            ret = proxy->end_sendDataReceiveHaptics(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 */
template<class T, typename CT> Callback_VRController_sendDataReceiveHapticsPtr
newCallback_VRController_sendDataReceiveHaptics(const IceUtil::Handle<T>& instance, void (T::*cb)(const Haptics&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRController_sendDataReceiveHaptics<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompVRController::VRController::begin_sendDataReceiveHaptics.
 */
template<class T, typename CT> Callback_VRController_sendDataReceiveHapticsPtr
newCallback_VRController_sendDataReceiveHaptics(T* instance, void (T::*cb)(const Haptics&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_VRController_sendDataReceiveHaptics<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
