//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VRControllerPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <VRControllerPub.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompVRControllerPub::VRControllerPub"
};
const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendControllers",
    "sendHaptics",
    "sendPoses"
};
const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name = "sendControllers";
const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name = "sendHaptics";
const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name = "sendPoses";

}

bool
RoboCompVRControllerPub::VRControllerPub::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompVRControllerPub_VRControllerPub_ids, iceC_RoboCompVRControllerPub_VRControllerPub_ids + 2, s);
}

::std::vector<::std::string>
RoboCompVRControllerPub::VRControllerPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompVRControllerPub_VRControllerPub_ids[0], &iceC_RoboCompVRControllerPub_VRControllerPub_ids[2]);
}

::std::string
RoboCompVRControllerPub::VRControllerPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompVRControllerPub::VRControllerPub::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompVRControllerPub::VRControllerPub";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceD_sendControllers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    Controller iceP_left;
    Controller iceP_right;
    istr->readAll(iceP_left, iceP_right);
    inS.endReadParams();
    this->sendControllers(::std::move(iceP_left), ::std::move(iceP_right), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceD_sendHaptics(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    Haptic iceP_left;
    Haptic iceP_right;
    istr->readAll(iceP_left, iceP_right);
    inS.endReadParams();
    this->sendHaptics(::std::move(iceP_left), ::std::move(iceP_right), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceD_sendPoses(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    Pose iceP_head;
    Pose iceP_left;
    Pose iceP_right;
    istr->readAll(iceP_head, iceP_left, iceP_right);
    inS.endReadParams();
    this->sendPoses(::std::move(iceP_head), ::std::move(iceP_left), ::std::move(iceP_right), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompVRControllerPub_VRControllerPub_ops, iceC_RoboCompVRControllerPub_VRControllerPub_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompVRControllerPub_VRControllerPub_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendControllers(in, current);
        }
        case 5:
        {
            return _iceD_sendHaptics(in, current);
        }
        case 6:
        {
            return _iceD_sendPoses(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRControllerPub::VRControllerPubPrx::_iceI_sendControllers(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const Controller& iceP_left, const Controller& iceP_right, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_left, iceP_right);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRControllerPub::VRControllerPubPrx::_iceI_sendHaptics(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const Haptic& iceP_left, const Haptic& iceP_right, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_left, iceP_right);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRControllerPub::VRControllerPubPrx::_iceI_sendPoses(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const Pose& iceP_head, const Pose& iceP_left, const Pose& iceP_right, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_head, iceP_left, iceP_right);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompVRControllerPub::VRControllerPubPrx::_newInstance() const
{
    return ::IceInternal::createProxy<VRControllerPubPrx>();
}
/// \endcond

const ::std::string&
RoboCompVRControllerPub::VRControllerPubPrx::ice_staticId()
{
    return VRControllerPub::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name = "sendControllers";

const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name = "sendHaptics";

const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name = "sendPoses";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompVRControllerPub::upCast(VRControllerPub* p) { return p; }

void
::IceProxy::RoboCompVRControllerPub::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< VRControllerPub>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new VRControllerPub;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompVRControllerPub::VRControllerPub::_iceI_begin_sendControllers(const ::RoboCompVRControllerPub::Controller& iceP_left, const ::RoboCompVRControllerPub::Controller& iceP_right, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_left);
        ostr->write(iceP_right);
        result->endWriteParams();
        result->invoke(iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompVRControllerPub::VRControllerPub::end_sendControllers(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompVRControllerPub_VRControllerPub_sendControllers_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompVRControllerPub::VRControllerPub::_iceI_begin_sendHaptics(const ::RoboCompVRControllerPub::Haptic& iceP_left, const ::RoboCompVRControllerPub::Haptic& iceP_right, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_left);
        ostr->write(iceP_right);
        result->endWriteParams();
        result->invoke(iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompVRControllerPub::VRControllerPub::end_sendHaptics(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompVRControllerPub_VRControllerPub_sendHaptics_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompVRControllerPub::VRControllerPub::_iceI_begin_sendPoses(const ::RoboCompVRControllerPub::Pose& iceP_head, const ::RoboCompVRControllerPub::Pose& iceP_left, const ::RoboCompVRControllerPub::Pose& iceP_right, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_head);
        ostr->write(iceP_left);
        ostr->write(iceP_right);
        result->endWriteParams();
        result->invoke(iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompVRControllerPub::VRControllerPub::end_sendPoses(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompVRControllerPub_VRControllerPub_sendPoses_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompVRControllerPub::VRControllerPub::_newInstance() const
{
    return new VRControllerPub;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompVRControllerPub::VRControllerPub::ice_staticId()
{
    return ::RoboCompVRControllerPub::VRControllerPub::ice_staticId();
}

RoboCompVRControllerPub::VRControllerPub::~VRControllerPub()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompVRControllerPub::upCast(VRControllerPub* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompVRControllerPub::VRControllerPub"
};

}

bool
RoboCompVRControllerPub::VRControllerPub::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompVRControllerPub_VRControllerPub_ids, iceC_RoboCompVRControllerPub_VRControllerPub_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompVRControllerPub::VRControllerPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompVRControllerPub_VRControllerPub_ids[0], &iceC_RoboCompVRControllerPub_VRControllerPub_ids[2]);
}

const ::std::string&
RoboCompVRControllerPub::VRControllerPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompVRControllerPub::VRControllerPub::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompVRControllerPub::VRControllerPub";
    return typeId;
#else
    return iceC_RoboCompVRControllerPub_VRControllerPub_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceD_sendControllers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    Controller iceP_left;
    Controller iceP_right;
    istr->read(iceP_left);
    istr->read(iceP_right);
    inS.endReadParams();
    this->sendControllers(iceP_left, iceP_right, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceD_sendHaptics(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    Haptic iceP_left;
    Haptic iceP_right;
    istr->read(iceP_left);
    istr->read(iceP_right);
    inS.endReadParams();
    this->sendHaptics(iceP_left, iceP_right, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceD_sendPoses(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    Pose iceP_head;
    Pose iceP_left;
    Pose iceP_right;
    istr->read(iceP_head);
    istr->read(iceP_left);
    istr->read(iceP_right);
    inS.endReadParams();
    this->sendPoses(iceP_head, iceP_left, iceP_right, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompVRControllerPub_VRControllerPub_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendControllers",
    "sendHaptics",
    "sendPoses"
};

}

/// \cond INTERNAL
bool
RoboCompVRControllerPub::VRControllerPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompVRControllerPub_VRControllerPub_all, iceC_RoboCompVRControllerPub_VRControllerPub_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompVRControllerPub_VRControllerPub_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendControllers(in, current);
        }
        case 5:
        {
            return _iceD_sendHaptics(in, current);
        }
        case 6:
        {
            return _iceD_sendPoses(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompVRControllerPub::VRControllerPub::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< VRControllerPub, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompVRControllerPub::VRControllerPub::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< VRControllerPub, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompVRControllerPub::_icePatchObjectPtr(VRControllerPubPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = VRControllerPubPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(VRControllerPub::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
